name: Deploy

on:
  workflow_dispatch:
    inputs:
      repo_ref:
        description: "Repo branch/tag reference"
        required: true
        default: "main"
      environment:
        description: "Environment name"
        required: true
        default: "test"

jobs:
  deploy:
    runs-on: win-scm

    environment:
      name: ${{ github.event.inputs.environment }}
      url: http://localhost

    steps:
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        env:
          USERNAME: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          script: |
            # Remove existing drive if exists
            if (Test-Path Z:) { Remove-SmbMapping -LocalPath Z: -Force }
            # Creating credential object using secret
            $cred = New-Object System.Management.Automation.PSCredential($env:USERNAME, (ConvertTo-SecureString $env:PASSWORD -AsPlainText -Force))
            # Mount remote share using credential object
            $drive = New-SmbMapping -RemotePath "\\${{ vars.SERVER_NAME }}\wwwroot" -LocalPath Z: -UserName $env:USERNAME -Password $env:PASSWORD

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.repo_ref }}

      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: |
            Copy-Item -Path .\* -Destination Z:\ -Recurse -Force -Verbose
