name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: win-scm

    steps:
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        env:
          USERNAME: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          script: |
            # Remove existing drive if exists
            if (Test-Path Z:) { Remove-PSDrive -Name Z -Force -ErrorAction SilentlyContinue }
            # Creating credential object using secret
            $cred = New-Object System.Management.Automation.PSCredential($env:USERNAME, (ConvertTo-SecureString $env:PASSWORD -AsPlainText -Force))
            # Mount remote share using credential object
            $drive = New-SmbMapping -RemotePath "\\web\wwwroot" -LocalPath Z: -UserName $env:USERNAME -Password $env:PASSWORD

      - name: checkout
        uses: actions/checkout@v2

      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        env:
          USERNAME: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          script: |
            # Creating credential object using secret
            $cred = New-Object System.Management.Automation.PSCredential($env:USERNAME, (ConvertTo-SecureString $env:PASSWORD -AsPlainText -Force))
            # Copy files using credential object
            Copy-Item -Path .\* -Destination Z:\ -Recurse -Force -Verbose -Credential $cred
